baseURL = 'https://alphaworks.com.br/'
title = 'Alphaworks'
theme = "hugo-theme-stack"
copyright = "Alphaworks"

# Language configuration
defaultContentLanguage = "pt-br"
hasCJKLanguage = false

[languages]
  [languages.pt-br]
    languageName = "Português"
    title = "Alphaworks"
    weight = 1
    [languages.pt-br.params]
      sidebar = { subtitle = "Inovação e Tecnologia" }

# Pagination
[pagination]
  pagerSize = 10

# Permalinks (standard for Stack)
[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

# Services (Disqus, Google Analytics - keep empty for now)
[services]
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

# Main parameters for the theme
[params]
  mainSections = ["posts"]
  featuredImageField = "image"
  rssFullContent = true

  footer = { since = 2023, customText = "Todos os direitos reservados." }

  dateFormat = { published = "Jan 02, 2006", lastUpdated = "Jan 02, 2006 15:04 MST" }

  sidebar = { emoji = "💡", subtitle = "Inovação e Tecnologia", avatar = { enabled = true, local = true, src = "/img/logo.png" } }
  
  article = { math = false, toc = true, readingTime = true, license = { enabled = false } }

  comments = { enabled = false }

  widgets = { homepage = [{ type = "search" }, { type = "archives", params = { limit = 5 } }, { type = "categories", params = { limit = 10 } }, { type = "tag-cloud", params = { limit = 10 } }], page = [{ type = "toc" }] }

  opengraph = { twitter = { site = "", card = "summary_large_image" } }

  defaultImage = { opengraph = { enabled = false, local = false, src = "" } }

  colorScheme = { toggle = true, default = "auto" }

  imageProcessing = { cover = { enabled = true }, content = { enabled = true } }

# Menu (empty for now, user can add later)
menu = { main = [], social = [] }

# Related posts (standard for Stack)
related = { includeNewer = true, threshold = 60, toLower = false, indices = [{ name = "tags", weight = 100 }, { name = "categories", weight = 200 }] }

# Markup configuration (standard for Stack)
markup = { goldmark = { extensions = { passthrough = { enable = true, delimiters = [{ block = ["[", "]"], inline = ["(", ")"] }] } }, renderer = { unsafe = true } }, tableOfContents = { endLevel = 4, ordered = true, startLevel = 2 }, highlight = { noClasses = false, codeFences = true, guessSyntax = true, lineNoStart = 1, lineNos = true, lineNumbersInTable = true, tabWidth = 4 } }

# Outputs (from user's current config)
[outputs]
  home = ["HTML", "RSS", "JSON", "Sitemap", "Sitemap"]