baseURL = 'https://alphaworks.com.br/'
defaultContentLanguage = "pt-br"
title = 'Alphaworks'
theme = "stack"
[pagination]
  pagerSize = 10

[params]
  description = "Alphaworks - tecnologia, inovação e produtividade."
  readmore = true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]

[params.logo]
  subtitle = "Inovação e Tecnologia"

[params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist"]

[params.widgets]
  recent_num = 5
  tags_counter = true

[sitemap]
  changefreq = "daily"
  priority = 0.5

# Para gerar sitemap de notícias
[outputs]
  home = ["HTML", "RSS", "JSON", "Sitemap", "Sitemap"]